project:
  name: quickstart-oracle-database
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - ap-northeast-1
    - ap-northeast-2
    #- ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    #- ca-central-1
    - eu-central-1
    - eu-west-1
    #- eu-west-2
    #- sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
tests:
  master-single-12201-ol73:
    parameters:
      AsmPass: $[taskcat_genpass_30]
      AvailabilityZones: $[taskcat_genaz_2]
      BastionInstanceType: t2.micro
      CharacterSet: AL32UTF8
      DataGuardConfig: Single
      DataIOPS: '600'
      DataVolumeType: io1
      DatabaseName: orcl
      DatabasePass: $[taskcat_genpass_30]
      DatabasePort: '1525'
      DomainName: dataguard-env
      EBSData: '20'
      EBSReco: '6'
      EnableCWL: 'true'
      InstallBucketName: override
      KeyPairName: $[taskcat_getkeypair]
      OSBBucketName: override
      OSBInstall: 'false'
      OSBKey: override
      OSBOTN: override
      OSBPass: override
      OSBSecret: override
      OracleAMIOS: Oracle-Linux-7.3-HVM
      OracleInstanceType: t2.large
      OracleVersion: 12.2.0.1
      PrimaryIPAddress: 10.0.0.5
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: aws-quickstart-develop
      RecoIOPS: '200'
      RecoVolumeType: io1
      RemoteAccessCIDR: 10.0.0.0/16
      StandbyIPAddress: 10.0.32.5
      StandbyName: orclsb
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - ap-northeast-1
      - ap-southeast-2
      - eu-central-1
      - us-east-1
      - us-west-1
    template: templates/oracle-database-master.template.yaml
  master-defaults-12201-rhel72:
    parameters:
      AsmPass: $[taskcat_genpass_30]
      AvailabilityZones: $[taskcat_genaz_2]
      BastionInstanceType: t2.micro
      CharacterSet: AL32UTF8
      DataGuardConfig: Data Guard
      DataIOPS: '600'
      DataVolumeType: gp2
      DatabaseName: orcl
      DatabasePass: $[taskcat_genpass_30]
      DatabasePort: '1525'
      DomainName: dataguard-env
      EBSData: '20'
      EBSReco: '6'
      EnableCWL: 'true'
      InstallBucketName: override
      KeyPairName: $[taskcat_getkeypair]
      OSBBucketName: override
      OSBInstall: 'false'
      OSBKey: override
      OSBOTN: override
      OSBPass: override
      OSBSecret: override
      OracleAMIOS: Red-Hat-Enterprise-Linux-7.2-HVM
      OracleInstanceType: t2.large
      OracleVersion: 12.2.0.1
      PrimaryIPAddress: 10.0.0.5
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: aws-quickstart-develop
      RecoIOPS: '200'
      RecoVolumeType: gp2
      RemoteAccessCIDR: 10.0.0.0/16
      StandbyIPAddress: 10.0.32.5
      StandbyName: orclsb
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - ap-south-1
      - ca-central-1
      - eu-west-1
      - us-east-2
      - us-west-2
    template: templates/oracle-database-master.template.yaml  
  master-defaults-12102-rhel72:
    parameters:
      AsmPass: $[taskcat_genpass_30]
      AvailabilityZones: $[taskcat_genaz_2]
      BastionInstanceType: t2.micro
      CharacterSet: AL32UTF8
      DataGuardConfig: Data Guard
      DataIOPS: '600'
      DataVolumeType: gp2
      DatabaseName: orcl
      DatabasePass: $[taskcat_genpass_30]
      DatabasePort: '1525'
      DomainName: dataguard-env
      EBSData: '20'
      EBSReco: '6'
      EnableCWL: 'true'
      InstallBucketName: override
      KeyPairName: $[taskcat_getkeypair]
      OSBBucketName: override
      OSBInstall: 'false'
      OSBKey: override
      OSBOTN: override
      OSBPass: override
      OSBSecret: override
      OracleAMIOS: Red-Hat-Enterprise-Linux-7.2-HVM
      OracleInstanceType: t2.large
      OracleVersion: 12.1.0.2
      PrimaryIPAddress: 10.0.0.5
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: aws-quickstart-develop
      RecoIOPS: '200'
      RecoVolumeType: gp2
      RemoteAccessCIDR: 10.0.0.0/16
      StandbyIPAddress: 10.0.32.5
      StandbyName: orclsb
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - ap-northeast-1
      - ap-south-1
      - ap-southeast-1
      - eu-central-1
      - us-east-2
    template: templates/oracle-database-master.template.yaml
  master-defaults-12201-ol73:
    parameters:
      AsmPass: $[taskcat_genpass_30]
      AvailabilityZones: $[taskcat_genaz_2]
      BastionInstanceType: t2.micro
      CharacterSet: AL32UTF8
      DataGuardConfig: Data Guard
      DataIOPS: '600'
      DataVolumeType: gp2
      DatabaseName: orcl
      DatabasePass: $[taskcat_genpass_30]
      DatabasePort: '1525'
      DomainName: dataguard-env
      EBSData: '20'
      EBSReco: '6'
      EnableCWL: 'true'
      InstallBucketName: override
      KeyPairName: $[taskcat_getkeypair]
      OSBBucketName: override
      OSBInstall: 'false'
      OSBKey: override
      OSBOTN: override
      OSBPass: override
      OSBSecret: override
      OracleAMIOS: Oracle-Linux-7.3-HVM
      OracleInstanceType: t2.large
      OracleVersion: 12.2.0.1
      PrimaryIPAddress: 10.0.0.5
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: aws-quickstart-develop
      RecoIOPS: '200'
      RecoVolumeType: gp2
      RemoteAccessCIDR: 10.0.0.0/16
      StandbyIPAddress: 10.0.32.5
      StandbyName: orclsb
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - ap-southeast-1
      - eu-central-1
      - eu-west-1
      - us-east-1
      - us-west-1
    template: templates/oracle-database-master.template.yaml
  master-single-12102-rhel72:
    parameters:
      AsmPass: $[taskcat_genpass_30]
      AvailabilityZones: $[taskcat_genaz_2]
      BastionInstanceType: t2.micro
      CharacterSet: AL32UTF8
      DataGuardConfig: Single
      DataIOPS: '600'
      DataVolumeType: io1
      DatabaseName: orcl
      DatabasePass: $[taskcat_genpass_30]
      DatabasePort: '1525'
      DomainName: dataguard-env
      EBSData: '20'
      EBSReco: '6'
      EnableCWL: 'true'
      InstallBucketName: override
      KeyPairName: $[taskcat_getkeypair]
      OSBBucketName: override
      OSBInstall: 'false'
      OSBKey: override
      OSBOTN: override
      OSBPass: override
      OSBSecret: override
      OracleAMIOS: Red-Hat-Enterprise-Linux-7.2-HVM
      OracleInstanceType: t2.large
      OracleVersion: 12.1.0.2
      PrimaryIPAddress: 10.0.0.5
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: aws-quickstart-develop
      RecoIOPS: '200'
      RecoVolumeType: io1
      RemoteAccessCIDR: 10.0.0.0/16
      StandbyIPAddress: 10.0.32.5
      StandbyName: orclsb
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - ap-south-1
      - ap-southeast-1
      - ca-central-1
      - eu-west-2
      - us-west-1
    template: templates/oracle-database-master.template.yaml
  master-single-12102-ol73:
    parameters:
      AsmPass: $[taskcat_genpass_30]
      AvailabilityZones: $[taskcat_genaz_2]
      BastionInstanceType: t2.micro
      CharacterSet: AL32UTF8
      DataGuardConfig: Single
      DataIOPS: '600'
      DataVolumeType: io1
      DatabaseName: orcl
      DatabasePass: $[taskcat_genpass_30]
      DatabasePort: '1525'
      DomainName: dataguard-env
      EBSData: '20'
      EBSReco: '6'
      EnableCWL: 'true'
      InstallBucketName: override
      KeyPairName: $[taskcat_getkeypair]
      OSBBucketName: override
      OSBInstall: 'false'
      OSBKey: override
      OSBOTN: override
      OSBPass: override
      OSBSecret: override
      OracleAMIOS: Oracle-Linux-7.3-HVM
      OracleInstanceType: t2.large
      OracleVersion: 12.1.0.2
      PrimaryIPAddress: 10.0.0.5
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: aws-quickstart-develop
      RecoIOPS: '200'
      RecoVolumeType: io1
      RemoteAccessCIDR: 10.0.0.0/16
      StandbyIPAddress: 10.0.32.5
      StandbyName: orclsb
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - ap-northeast-1
      - ap-northeast-2
      - ap-southeast-2
      - eu-central-1
      - us-west-2
    template: templates/oracle-database-master.template.yaml  
  master-defaults-12102-ol73:
    parameters:
      AsmPass: $[taskcat_genpass_30]
      AvailabilityZones: $[taskcat_genaz_2]
      BastionInstanceType: t2.micro
      CharacterSet: AL32UTF8
      DataGuardConfig: Data Guard
      DataIOPS: '600'
      DataVolumeType: gp2
      DatabaseName: orcl
      DatabasePass: $[taskcat_genpass_30]
      DatabasePort: '1525'
      DomainName: dataguard-env
      EBSData: '20'
      EBSReco: '6'
      EnableCWL: 'true'
      InstallBucketName: override
      KeyPairName: $[taskcat_getkeypair]
      OSBBucketName: override
      OSBInstall: 'false'
      OSBKey: override
      OSBOTN: override
      OSBPass: override
      OSBSecret: override
      OracleAMIOS: Oracle-Linux-7.3-HVM
      OracleInstanceType: t2.large
      OracleVersion: 12.1.0.2
      PrimaryIPAddress: 10.0.0.5
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: aws-quickstart-develop
      RecoIOPS: '200'
      RecoVolumeType: gp2
      RemoteAccessCIDR: 10.0.0.0/16
      StandbyIPAddress: 10.0.32.5
      StandbyName: orclsb
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - ap-northeast-1
      - ap-southeast-1
      - eu-west-1
      - us-east-1
      - us-west-1
    template: templates/oracle-database-master.template.yaml
  master-single-12201-rhel72:
    parameters:
      AsmPass: $[taskcat_genpass_30]
      AvailabilityZones: $[taskcat_genaz_2]
      BastionInstanceType: t2.micro
      CharacterSet: AL32UTF8
      DataGuardConfig: Single
      DataIOPS: '600'
      DataVolumeType: io1
      DatabaseName: orcl
      DatabasePass: $[taskcat_genpass_30]
      DatabasePort: '1525'
      DomainName: dataguard-env
      EBSData: '20'
      EBSReco: '6'
      EnableCWL: 'true'
      InstallBucketName: override
      KeyPairName: $[taskcat_getkeypair]
      OSBBucketName: override
      OSBInstall: 'false'
      OSBKey: override
      OSBOTN: override
      OSBPass: override
      OSBSecret: override
      OracleAMIOS: Red-Hat-Enterprise-Linux-7.2-HVM
      OracleInstanceType: t2.large
      OracleVersion: 12.2.0.1
      PrimaryIPAddress: 10.0.0.5
      PrivateSubnet1CIDR: 10.0.0.0/19
      PrivateSubnet2CIDR: 10.0.32.0/19
      PublicSubnet1CIDR: 10.0.128.0/20
      PublicSubnet2CIDR: 10.0.144.0/20
      QSS3BucketName: aws-quickstart-develop
      RecoIOPS: '200'
      RecoVolumeType: io1
      RemoteAccessCIDR: 10.0.0.0/16
      StandbyIPAddress: 10.0.32.5
      StandbyName: orclsb
      VPCCIDR: 10.0.0.0/16
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
    regions:
      - ap-northeast-2
      - ap-south-1
      - ap-southeast-2
      - eu-west-2
      - us-east-2
    template: templates/oracle-database-master.template.yaml  